/init_locations : J152 J209 J229
/use_sim_time : True
/gui : False
/graph : pipeline1
/init_bots : 3
/done : False
/sim_length : 30000
/algo_name : iot_communication_network
/no_of_deads : 0
/random_string : test
/deploy_tag : graph
/no_of_base_stations : 62
/iot_device_range : 100